from ExternalAGIStuff.CodeVisualization.code_editor import find_middle
from ExternalAGIStuff.CodeVisualization.StructureVisualization.translate_AGIObject import translate_AGIObject
from ExternalAGIStuff.IDs.reserved_keywords import rr
from ExternalAGIStuff.code_to_object import code_to_object
from ElephantChessInstance.FormattedCode.operation_func_f import operation_func_f
result = translate_AGIObject(code_to_object(operation_func_f))
print(result)

