r = {
    'input': 1,
    'return': 2,
    'reg': 3,
    'iterator': 4,
    'assign': 5,
    'assign_as_reference': 6,
    'system_call': 7,
    'call': 8,
    'system_type': 9,
    'concept_instance': 10,
    'assert': 11,
    'for': 14,
    'while': 15,
    'break': 16,
    'if': 17,
    'size': 18,
    'get_member': 19,
    'get_concept_id': 20,
    'at': 21,
    'at_reverse': 22,
    'append': 23,
    'remove': 24,
    'find': 25,
    'exist': 26,
    'request': 27
}